name: Test

on: ['push', 'pull_request']

jobs:
  code:
    name: Test code
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: 01f6a48f4e3b0b9936f9939e98ae1d3906d7b22d
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run migrations
        run: yarn prisma migrate deploy

      - name: Run Jest
        run: yarn test --coverage --passWithNoTests

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
